name: Azure Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env variables
        run: |
          cp .env.example .env
          php artisan config:clear

      - name: Generate app key
        run: php artisan key:generate

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: backendbdd2
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
